spring.application.name=Bau do Capitao Api
spring.data.mongodb.uri=mongodb+srv://eduardotellussanesul_db_user:VrIxcYvHsF4AV1Qn@baucapitao.vfzvek2.mongodb.net/?retryWrites=true&w=majority&ssl=true&tls=true
spring.data.mongodb.database=bau_do_capitao
spring.data.mongodb.ssl.enabled=true
spring.data.mongodb.ssl.invalid-host-name-allowed=false